Repository Teamingg/Frontend, pull requests merged in 2025-03, with the labels that each got.

#23 ♻️ Refactor: My Account 버그 픽스 및 Header 컴포넌트 최적화
  src/app/my/dashboard/page.tsx
  src/app/sign-up/_components/SignUpUserForm.tsx
  src/components/Card/StatusCard.tsx
  src/components/Card/index.ts
  src/components/Logo/Logo.tsx
  src/components/Logo/index.ts
  src/components/My/EditUserForm.tsx
  src/components/My/UserInfoForm.tsx
  src/components/Team/TeamHeader.tsx
  src/hooks/queries/my/myPageKeys.ts
  src/layout/Header.tsx
  src/layout/Navigation/GlobalNavigation.tsx
  src/middleware.ts
Labels: bug, Components

#25 :sparkle: feat - team dashboard 내부 컴포넌트 개성
  .gitignore
  src/app/form/[form_type]/[page_type]/page.tsx
  src/app/my/[type]/page.tsx
  src/app/my/dashboard/page.tsx
  src/app/my/layout.tsx
  src/app/my/review/page.tsx
  src/app/sign-up/_components/SignUpUserForm.tsx
  src/app/team/[type]/[id]/(info)/dashboard/page.tsx
  src/app/team/[type]/[id]/(info)/layout.tsx
  src/app/team/[type]/[id]/info/layout.tsx
  src/app/team/[type]/[id]/info/page.tsx
  src/app/team/[type]/[id]/layout.tsx
  src/app/team/[type]/[id]/member/_layout.tsx
  src/app/team/[type]/[id]/member/page.tsx
  src/components/Badge/BadgeList.tsx
  src/components/ProgressBar.tsx
  src/components/Team/ProjectInfo.tsx
  src/components/Team/TeamBasicInfo.tsx
  src/hooks/useDataMap.tsx
  src/service/api/my/getMyInfo.ts
  src/service/api/my/getMyMentoringTeam.ts
  src/service/api/my/getMyProjectTeam.ts
  src/service/api/my/getMyReview.ts
  src/service/api/my/index.ts
  src/service/api/team/participate.ts
  src/service/api/team/team.ts
  src/service/getProgress.ts
  src/types/UserInfoFormValues.d.ts
Labels: :bug: Bug, :sparkle: Feature

#29 [Feat] SSE 알림 기능 구현
  src/app/(Auth)/sign-up/_components/SignUpUserForm.tsx
  src/app/(Auth)/sign-up/page.tsx
  src/app/layout.tsx
  src/components/Notification.tsx
  src/components/notification/NotificationItem.tsx
  src/components/notification/NotificationList.tsx
  src/layout/Navigation/GlobalNavigation.tsx
  src/middleware.ts
  src/service/api/getNotification.ts
  src/service/api/my/getMyMentoringTeam.ts
  src/service/api/my/getMyProjectTeam.ts
  src/service/api/notification/connectNotification.ts
  src/service/api/notification/notification.ts
  src/types/UserInfoFormValues.d.ts
  src/types/notification.d.ts
Labels: :sparkle: Feature

#30 ♻️ refactor - 멘토링 팀 생성 폼 유효성 검사 추가 및 불필요한 로그 삭제
  src/app/form/[[...form]]/page.tsx
  src/app/form/post/page.tsx
  src/app/globals.css
  src/app/team/_[type]/[id]/(info)/dashboard/page.tsx
  src/app/team/_[type]/[id]/(info)/layout.tsx
  src/app/team/_[type]/[id]/(info)/viewer/page.tsx
  src/app/team/_[type]/[id]/layout.tsx
  src/app/team/_[type]/[id]/member/layoutDump.tsx
  src/app/team/_[type]/[id]/member/page.tsx
  src/app/team/_[type]/[id]/post/layout.tsx
  src/app/team/_[type]/[id]/post/page.tsx
  src/components/Button/Button.tsx
  src/components/Form/MentoringForm.tsx
  src/components/Form/ProjectForm.tsx
  src/components/Form/ProjectFormDump.tsx
  src/components/Input/Select.tsx
  src/types/team/team.d.ts
Labels: :recycle: Refactoring
